#macro		keyLeft		vk_left
#macro		keyRight	vk_right
#macro		keyUp		vk_up
#macro		keyDown		vk_down
#macro		keyA		ord("Z")
#macro		keyB		ord("X")
#macro		keyL		ord("A")
#macro		keyR		ord("S")
#macro		keyStart	vk_return
#macro		keyOption	vk_shift
